// pvz.idl : type library source for pvz.exe

// This file will be processed by the MIDL compiler to produce the
// type library (pvz.tlb).

[ uuid(492f2e9a-e4da-477e-aa6c-a146ba05a435), version(1.0) ]
library pvz
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	//  Primary dispatch interface for CpvzDoc

	[ uuid(e49e3495-9343-466f-ba14-f2d29aefc0cf) ]
	dispinterface Ipvz
	{
		properties:

		methods:
	};

	//  Class information for CpvzDoc

	[ uuid(2c259e82-0471-4749-b7ca-e7a0595938ae) ]
	coclass pvz
	{
		[default] dispinterface Ipvz;
	};
};
